// KiqAppController
// Generated by Kiq
// April 13th 2017, 1:07 PM

var KiqBase = require('kiq').controllers.base;

class KiqAppController extends KiqBase {

  initialize() {

    // Define your before and after filters here
 
    // Before filters are called before reaching the action code
    // You can choose to 'reply' and halt the action pipeline like this
    // this.beforeAction(( reply, error, req, res ) => {
    //   reply({message: 'My before action'});
    // });
 
    // Use an after filter to do something post action
    // this.afterAction(() => {
    //   console.log({message: 'My after action'});
    // });

  }

  index( reply, error, req, res ) {

    reply({
      controller: 'KiqApp',
      action: 'index',
      params: Object.assign({}, req.params, req.query)
    });

  }

}

module.exports = KiqAppController;